CREATE TABLE Users (
	username VARCHAR(30) NOT NULL,
	name VARCHAR(70) NOT NULL,
	email VARCHAR(40) NOT NULL,
	password VARCHAR(30) NOT NULL,
	PRIMARY KEY(username)
)ENGINE = InnoDB;

CREATE TABLE Groups (
	groupID SMALLINT(5) NOT NULL AUTO_INCREMENT,
	name VARCHAR(70) NOT NULL,
	purpose TEXT NOT NULL,
	PRIMARY KEY(groupID)
)ENGINE = InnoDB;

CREATE TABLE Events (
	eventID SMALLINT(5) NOT NULL AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL,
	endDate DATE NOT NULL,
	endTime TIME NOT NULL,
	initDate DATE NOT NULL,
	initTime TIME NOT NULL,
	subject TEXT NOT NULL,
	repeatType TINYINT(1) NOT NULL,
	repeatAmt TINYINT(3) NOT NULL,
	PRIMARY KEY(eventID)
)ENGINE = InnoDB;

CREATE TABLE UserCreateEvents (
	creator VARCHAR(30) NOT NULL,
	eventID SMALLINT(5) NOT NULL,
	FOREIGN KEY fk_userCreator(creator) REFERENCES Users(username)
	ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY fk_userCrtEvent(eventID) REFERENCES Events(eventID)
	ON UPDATE RESTRICT ON DELETE CASCADE
)ENGINE = InnoDB;

CREATE TABLE GroupCreateEvents (
	groupID SMALLINT(5) NOT NULL,
	eventID SMALLINT(5) NOT NULL,
	FOREIGN KEY fk_groupCreator(groupID) REFERENCES Groups(groupID)
	ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY fk_grpCrtEvent(eventID) REFERENCES Events(eventID)
	ON UPDATE RESTRICT ON DELETE CASCADE
)ENGINE = InnoDB;

CREATE TABLE UserMessages(
	sender VARCHAR(30) NOT NULL,
	receiver VARCHAR(30) NOT NULL,
	msgStamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	content TEXT NOT NULL,
	FOREIGN KEY fk_userUserSend(sender) REFERENCES Users(username)
	ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY fk_userReceive(receiver) REFERENCES Users(username)
	ON UPDATE RESTRICT ON DELETE CASCADE
)ENGINE = InnoDB;

CREATE TABLE GroupMessages(
	sender VARCHAR(30) NOT NULL,
	receiver SMALLINT(5) NOT NULL,
	msgStamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	content TEXT NOT NULL,
	FOREIGN KEY fk_userGrpSend(sender) REFERENCES Users(username)
	ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY fk_grpReceive(receiver) REFERENCES Groups(groupID)
	ON UPDATE RESTRICT ON DELETE CASCADE
)ENGINE = InnoDB;

CREATE TABLE InGroup (
	username VARCHAR(30) NOT NULL,
	groupID SMALLINT(5) NOT NULL,
	FOREIGN KEY fk_participant(username) REFERENCES Users(username)
	ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY fk_group(groupID) REFERENCES Groups(groupID)
	ON UPDATE RESTRICT ON DELETE CASCADE
)ENGINE = InnoDB;

CREATE TABLE UserEvents (
	username VARCHAR(30) NOT NULL,
	eventID SMALLINT(5) NOT NULL,
	FOREIGN KEY fk_eventOwner(username) REFERENCES Users(username)
	ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY fk_event(eventID) REFERENCES Events(eventID)
	ON UPDATE RESTRICT ON DELETE CASCADE
)ENGINE = InnoDB;

CREATE TABLE ComposedEvents (
	parentEvent SMALLINT(5) NOT NULL,
	childEvent SMALLINT (5) NOT NULL,
	FOREIGN KEY fk_parentE(parentEvent) REFERENCES Events(eventID)
	ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY fk_childE(childEvent) REFERENCES Events(eventID)
	ON UPDATE RESTRICT ON DELETE CASCADE
)ENGINE = InnoDB;